name: lab_7_416778_test

on:
  push:
    branches:
      - roboczy

jobs:
  test_dodawanie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install -r Lab_7/env_416778/requirements.txt
      - run: cd Lab_7/env_416778 && pytest -k test_dodawanie calculator_test.py

  test_odejmowanie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install -r Lab_7/env_416778/requirements.txt
      - run: cd Lab_7/env_416778 && pytest -k test_odejmowanie calculator_test.py

  test_mnozenie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install -r Lab_7/env_416778/requirements.txt
      - run: cd Lab_7/env_416778 && pytest -k test_mnozenie calculator_test.py

  test_dzielenie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install -r Lab_7/env_416778/requirements.txt
      - run: cd Lab_7/env_416778 && pytest -k test_dzielenie calculator_test.py

  new_test:
    needs: [test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install -r Lab_7/env_416778/requirements.txt
      - run: cd Lab_7/env_416778 && pytest new_test.py
