name: lab_7_416778_test

on:
  push:
    branches:
      - roboczy

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      python-path: ${{ steps.setpath.outputs.path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd ./Lab_7/env_416778
          pip install -r requirements.txt

  test_dodawanie:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd ./Lab_7/env_416778
          pip install -r requirements.txt
      - name: Run dodawanie test
        run: |
          cd ./Lab_7/env_416778
          pytest -k test_dodawanie calculator_test.py

  test_odejmowanie:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd ./Lab_7/env_416778
          pip install -r requirements.txt
      - name: Run odejmowanie test
        run: |
          cd ./Lab_7/env_416778
          pytest -k test_odejmowanie calculator_test.py

  test_mnozenie:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd ./Lab_7/env_416778
          pip install -r requirements.txt
      - name: Run mnozenie test
        run: |
          cd ./Lab_7/env_416778
          pytest -k test_mnozenie calculator_test.py

  test_dzielenie:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd ./Lab_7/env_416778
          pip install -r requirements.txt
      - name: Run dzielenie test
        run: |
          cd ./Lab_7/env_416778
          pytest -k test_dzielenie calculator_test.py

  test_suma_kolumny:
    needs: [prepare, test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd ./Lab_7/env_416778
          pip install -r requirements.txt
      - name: Run new calculator tests
        run: |
          cd ./Lab_7/env_416778
          pytest -k test_suma_kolumny calculator_test.py

  test_srednia_kolumny:
    needs: [prepare, test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd ./Lab_7/env_416778
          pip install -r requirements.txt
      - name: Run new calculator tests
        run: |
          cd ./Lab_7/env_416778
          pytest -k test_srednia_kolumny calculator_test.py
